// File generated by FlutterFire CLI.
// Run `dart pub global activate flutterfire_cli && flutterfire configure` to replace placeholders.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHOXc5HKW8J_15IuD93ypm_8Ps1K3BYs',
    appId: '1:117321124521:web:932abbad828113427177b8',
    messagingSenderId: '117321124521',
    projectId: 'molly-expenses',
    authDomain: 'molly-expenses.firebaseapp.com',
    storageBucket: 'molly-expenses.firebasestorage.app',
    measurementId: 'G-VJCLPFRDC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBypDbBGhCCIntVerARZyUPgnku0Y3ZDc',
    appId: '1:117321124521:android:9c6df914f9c0c1127177b8',
    messagingSenderId: '117321124521',
    projectId: 'molly-expenses',
    storageBucket: 'molly-expenses.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOhFJcJuXswfW7uvFuIy8T5B9c1HBbSY',
    appId: '1:117321124521:ios:9b03277faed10fdd7177b8',
    messagingSenderId: '117321124521',
    projectId: 'molly-expenses',
    storageBucket: 'molly-expenses.firebasestorage.app',
    iosBundleId: 'com.mollyexpenses.mollyExpenses',
  );
}
